# GY-MAX4466 is an analog module, so we need to enable the ADC driver
CONFIG_ADC=y

# Console Output
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_PRINTK=y

# Enable logging
CONFIG_LOG=y


